apiVersion: v1
kind: ConfigMap
metadata:
  name: python-application-configmap
  namespace: {{ .Values.namespace }}
data:
  index.html: |
    this is a basic html file showing you how to serve static files using a configmap    

