apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
  namespace: omer
  labels:
    {{- include "pythonApp.labels" . }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pythonApp.labels" . | indent 2 }}
  template:
    metadata:
      labels:
        {{- include "pythonApp.labels" . | indent 4 }}
    spec:
      containers:
      - name: python-app
        image: {{ .Values.pythonApp.image }}:{{ .Values.pythonApp.tag }}
        ports:
        - containerPort: 8000
