apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.pythonApp.name -}}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pythonApp.labels" . }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pythonApp.labels" . | indent 2 }}
  template:
    metadata:
      labels:
        {{- include "pythonApp.labels" . | indent 4 }}
    spec:
      containers:
      - name: {{ .Values.pythonApp.name }}
        image: {{ .Values.pythonApp.image }}:{{ .Values.pythonApp.tag }}
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: {{ .Values.pythonApp.name -}}-volume
          mountPath: {{ .Values.pythonApp.baseDir }}
        command: ["python3"]
        args: ["-m", "http.server", "--bind", "0.0.0.0", "8000", "--directory", {{ .Values.pythonApp.baseDir }}]
      volumes:
        - name: {{ .Values.pythonApp.name -}}-volume
          configMap:
            name: {{ .Values.pythonApp.name -}}-configmap
