apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
  namespace: omer
  labels:
    {{ include "pythonApp.labels" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{ include "pythonApp.labels" . }}
  template:
    metadata:
      labels:
        {{ include "pythonApp.labels" . }}
    spec:
      containers:
      - name: python-app
        image: {{ .Values.pythonApp.image }}:{{ .Values.pythonApp.tag }}
        ports:
        - containerPort: 8000
