apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pythonApp.name -}}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    {{- include "pythonApp.labels" . }}
  type: LoadBalancer
  ports:
    - protocol: TCP
      targetPort: 8000
      port: 80     

