apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: omer
spec:
  selector:
    {{- include "pythonApp.labels" . }}
  type: LoadBalancer
  ports:
    - protocol: TCP
      targetPort: 8000
      port: 80     

