apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: omer
spec:
  selector:
    app: python-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      targetPort: 8000
      port: 8000      

