name: deploy-python-app-chart
on:
  push:
    branches:
      - main
    paths:
      - 'charts/python-application/**'
jobs:
  deploy_to_eks:
    name: Set up helm and deploy chart to eks
    runs-on: ubuntu-latest
    environment: eks
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: helm deploy
        uses: koslib/helm-eks-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
        with:
          command: helm upgrade python-application --install --wait charts/python-application

