name: deploy-python-app-chart
on:
  push:
    branches:
      - main
    paths:
      - 'charts/python-application/**'
jobs:
  deploy_to_eks:
    name: Set up helm and deploy chart to eks
    runs-on: ubuntu-latest
    environment: eks
    steps:
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.0
        id: install

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Create KubeConfig
        run: |
          mkdir $HOME/.kube/
          echo ${{ secrets.KUBECONFIG}} > $HOME/.kube/config

      - name: Install or Upgrade the chart
        run: |
          helm upgrade python-application --install --wait charts/python-application
