name: deploy-python-app-chart
on:
  push:
    branches:
      - main
    paths:
      - 'charts/python-application/**'
jobs:
  deploy_to_eks:
    name: Set up helm and deploy chart to eks
    runs-on: ubuntu-latest
    steps:
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.0
        id: install
     
      - name: Deploy the chart
        uses: craftech-io/eks-helm-deploy-action@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS__KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          cluster-name: ${{ secrets.CLUSTER_NAME }}
          chart-path: charts/python-application
          name: python-app-${{ github.sha }}
