name: deploy-python-app-chart
on:
  push:
    branches:
      - main
    paths:
      - 'charts/python-application/**'
jobs:
  deploy_to_eks:
    name: Set up helm and deploy chart to eks
    runs-on: ubuntu-latest
    steps:
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.0
        id: install

      - name: Check out the repo
        uses: actions/checkout@v2
    
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: helm deploy
        uses: koslib/helm-eks-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG}}
        with:
          command: helm upgrade python-application --install --wait charts/python-application

